### ISSUE TITLE
Own name not displaying in chats

### ISSUE THREAD

**Issue by sysr-q** [PeteDevoy/irc-style-for-messenger-com#1]
This seems to be due to `#facebook .accessible_elem` getting priority over your `h5._ih3._-ne` rule.
Updating the h5 rule like this fixes it and doesn't seem to interfere with other parts of the theme that I can see:

```css
h5._ih3 {
    margin: 0;
    padding: 0;
    height: auto !important;
    width: auto !important;
    position: relative !important;
}
``` 

That is, removing the `_-ne` and adding height, width, position. That also fixes your own name displaying correctly in groups, as well as the padding for names in groups so that people's names are slightly left of their messages.
